let actionTypes = {
    APIINFO_FETCH_SUCCESS: 'APIINFO_FETCH_SUCCESS',

    REGISTRATION_SUBMISSION_SUCCESS: 'REGISTRATION_SUBMISSION_SUCCESS',
    REGISTRATION_SUBMISSION_ERROR: 'REGISTRATION_SUBMISSION_ERROR',

    FETCH_BOOKINGS_SUCCESS: 'FETCH_BOOKINGS_SUCCESS',

    VALIDATE_FORM_SUCCESS: 'VALIDATE_FORM_SUCCESS',
};

export default actionTypes;
